#ifndef LIBVMI_CONF_FILE_COMMON_H
#define LIBVMI_CONF_FILE_COMMON_H

#include "tiny_private.h"


// #if ENABLE_LINUX == 1

// include system map or rekall files as hardcoded strings.
#include "./target_conf/target_libvmi_sym.h"

// #endif // ENABLE_LINUX == 1

/*
* the following char array is auto generated by unix command 
*       $ xxd -i libvmi.conf
*/


extern unsigned char libvmi_conf[] ;

extern unsigned int libvmi_conf_len ;


/*
* in: char* vm_name
*
* in: char[] libvmi_conf: defined in libvmi_conf_file.h, act as 
*		string version of config file in ~/etc/libvmi.conf in the
*		original LibVMI.
* out/return: char * config: configure string for vm_name
*
*/

char * get_config_from_file_string(char *vm_name);

/*
* in: char* config: configure string
* out: config_ht: configure in hashtable
*/
GHashTable * get_config_hashtable_from_string(char *config);

#endif //LIBVMI_CONF_FILE_COMMON_H
